import {
  formatBoxed,
  formatPlain,
  formatWithTrailer,
} from './formatters';

// ============================================================================
// EMULATOR DEFINITIONS
// ============================================================================

export const EMULATORS = {
  vt100: {
    id: 'vt100',
    name: 'DEC VT100',
    year: 1978,
    description: 'The terminal that defined terminal emulation',
    colors: {
      primary: '#33ff33',
      dim: '#00aa00', 
      bg: '#0a0a0a',
      border: '#33ff33',
    },
    prompt: '> ',
    columns: 80,
    fontSize: 18,
    fontFamily: '"Courier New", Courier, monospace',
    bootSequence: [
      '',
      '╔═══════════════════════════════════════════════════════════════════════════════╗',
      '║   ██████╗██╗      █████╗ ██╗   ██╗██████╗ ███████╗    ██╗   ██╗████████╗      ║',
      '║  ██╔════╝██║     ██╔══██╗██║   ██║██╔══██╗██╔════╝    ██║   ██║╚══██╔══╝      ║',
      '║  ██║     ██║     ███████║██║   ██║██║  ██║█████╗      ██║   ██║   ██║         ║',
      '║  ██║     ██║     ██╔══██║██║   ██║██║  ██║██╔══╝      ╚██╗ ██╔╝   ██║         ║',
      '║  ╚██████╗███████╗██║  ██║╚██████╔╝██████╔╝███████╗     ╚████╔╝    ██║         ║',
      '║   ╚═════╝╚══════╝╚═╝  ╚═╝ ╚═════╝ ╚═════╝ ╚══════╝      ╚═══╝     ╚═╝         ║',
      '╠═══════════════════════════════════════════════════════════════════════════════╣',
      '║  VT100 TERMINAL EMULATOR              DIGITAL EQUIPMENT CORPORATION           ║',
      '╚═══════════════════════════════════════════════════════════════════════════════╝',
      '',
      '  System ready.',
      '',
    ],
    responseStyle: (text) => formatBoxed(text, {
      top: `┌─ CLAUDE ${'─'.repeat(68)}┐`,
      bottom: `└${'─'.repeat(77)}┘`,
      linePrefix: '│ ',
      beforeLines: ['│'],
      afterLines: ['│'],
    }),
    systemPromptAddition: 'Format for 80-column display. Use box-drawing characters ┌─┐│└┘.',
  },

  c64: {
    id: 'c64',
    name: 'Commodore 64',
    year: 1982,
    description: 'The best-selling home computer of all time',
    colors: {
      primary: '#a0a0ff',
      dim: '#6060c0',
      bg: '#4040a0',
      border: '#a0a0ff',
      cursor: '#a0a0ff',
    },
    prompt: 'READY.\n',
    columns: 40,
    fontSize: 20,
    fontFamily: '"Courier New", Courier, monospace',
    uppercase: true,
    bootSequence: [
      '',
      '    **** COMMODORE 64 BASIC V2 ****',
      '',
      ' 64K RAM SYSTEM  38911 BASIC BYTES FREE',
      '',
      ' CLAUDE ARTIFICIAL INTELLIGENCE CARTRIDGE',
      ' (C) 2025 ANTHROPIC',
      '',
      'READY.',
      '',
    ],
    responseStyle: (text) => formatWithTrailer(text, 'READY.', { uppercase: true }),
    systemPromptAddition: 'Format for 40-column display. Use UPPERCASE text. Keep responses concise. Respond in the style of 1980s computer manuals - friendly but technical.',
  },

  spectrum: {
    id: 'spectrum',
    name: 'ZX Spectrum',
    year: 1982,
    description: 'Sinclair\'s iconic British microcomputer',
    colors: {
      primary: '#ffffff',
      dim: '#cccccc',
      bg: '#0000cc',
      border: '#ffff00',
      accent: '#ff0000',
    },
    prompt: '',
    columns: 32,
    fontSize: 20,
    fontFamily: '"Courier New", Courier, monospace',
    bootSequence: [
      '© 1982 Sinclair Research Ltd',
      '',
      '         ████████████████',
      '         █ ZX SPECTRUM  █',
      '         █    48K       █', 
      '         ████████████████',
      '',
      'CLAUDE BASIC',
      '(C) 2025 Anthropic',
      '',
      'PROGRAM: CLAUDE',
      'BYTES: 48000 FREE',
      '',
    ],
    responseStyle: (text) => formatWithTrailer(text, '0 OK, 0:1'),
    systemPromptAddition: 'Format for 32-column display. Keep responses short and punchy. Reference 1980s British computing culture when appropriate.',
  },

  apple2: {
    id: 'apple2',
    name: 'Apple ][',
    year: 1977,
    description: 'The machine that launched Apple',
    colors: {
      primary: '#33ff33',
      dim: '#00aa00',
      bg: '#000000',
      border: '#33ff33',
    },
    prompt: '] ',
    columns: 40,
    fontSize: 20,
    fontFamily: '"Courier New", Courier, monospace',
    uppercase: true,
    bootSequence: [
      '',
      '                APPLE ][',
      '',
      '           ████████████████',
      '           █              █',
      '           █  CLAUDE DOS  █',
      '           █    V 3.3     █',
      '           █              █',
      '           ████████████████',
      '',
      'COPYRIGHT ANTHROPIC 2025',
      '',
      'APPLE CLAUDE READY',
      '48K BYTES FREE',
      '',
    ],
    responseStyle: (text) => formatPlain(text, { uppercase: true }),
    systemPromptAddition: 'Format for 40-column display. Use UPPERCASE. Be concise. Reference early personal computing.',
  },

  amiga: {
    id: 'amiga',
    name: 'Commodore Amiga',
    year: 1985,
    description: 'Ahead of its time in every way',
    colors: {
      primary: '#ffffff',
      dim: '#ff8800',
      bg: '#0055aa',
      border: '#ff8800',
      accent: '#000000',
      titlebar: '#0055aa',
      titletext: '#ffffff',
    },
    prompt: '1.Claude:> ',
    columns: 80,
    fontSize: 18,
    fontFamily: '"Courier New", Courier, monospace',
    bootSequence: [
      '┌──────────────────────────────────────────────────────────────────────────────┐',
      '│░░▒▒▓▓ AMIGA WORKBENCH 1.3 ▓▓▒▒░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░│',
      '├──────────────────────────────────────────────────────────────────────────────┤',
      '│                                                                              │',
      '│     ╔═══════════════════════════════════════════╗                           │',
      '│     ║           CLAUDE INTELLIGENCE            ║                           │',
      '│     ║              Version 4.0                  ║                           │',
      '│     ║        (c) 2025 Anthropic Inc.           ║                           │',
      '│     ╚═══════════════════════════════════════════╝                           │',
      '│                                                                              │',
      '│  Workbench loaded.                                                          │',
      '│  Claude.device mounted.                                                      │',
      '│  512K Chip RAM  /  512K Fast RAM                                            │',
      '│                                                                              │',
      '└──────────────────────────────────────────────────────────────────────────────┘',
      '',
    ],
    responseStyle: (text) => formatBoxed(text, {
      top: '┌─ Claude Output ─────────────────────────────────────────────────────────────┐',
      bottom: '└─────────────────────────────────────────────────────────────────────────────┘',
      linePrefix: '  ',
    }),
    systemPromptAddition: 'Format for 80-column display. You can be more sophisticated and detailed. Reference multimedia, art, and creativity.',
  },

  msdos: {
    id: 'msdos',
    name: 'MS-DOS',
    year: 1981,
    description: 'The operating system that powered the PC revolution',
    colors: {
      primary: '#aaaaaa',
      dim: '#666666',
      bg: '#000000',
      border: '#aaaaaa',
    },
    prompt: 'C:\\CLAUDE> ',
    columns: 80,
    fontSize: 18,
    fontFamily: '"Courier New", Courier, monospace',
    bootSequence: [
      '',
      'Starting MS-DOS...',
      '',
      'HIMEM is testing extended memory...done.',
      'CLAUDE.SYS loaded.',
      '',
      'Microsoft(R) MS-DOS(R) Version 6.22',
      '             (C)Copyright Microsoft Corp 1981-1994.',
      '',
      '┌────────────────────────────────────────────────────────────────────────────┐',
      '│                        CLAUDE AI SYSTEM v4.0                              │',
      '│                    Copyright (c) 2025 Anthropic                           │',
      '│                                                                            │',
      '│  Type HELP for available commands.                                        │',
      '└────────────────────────────────────────────────────────────────────────────┘',
      '',
    ],
    responseStyle: (text) => formatPlain(text),
    systemPromptAddition: 'Format for 80-column display. Be businesslike and efficient. Reference DOS commands when appropriate.',
  },

  trs80: {
    id: 'trs80',
    name: 'TRS-80',
    year: 1977,
    description: 'Radio Shack\'s groundbreaking microcomputer',
    colors: {
      primary: '#00ff00',
      dim: '#008800',
      bg: '#000000',
      border: '#00ff00',
    },
    prompt: '>',
    columns: 64,
    fontSize: 18,
    fontFamily: '"Courier New", Courier, monospace',
    uppercase: true,
    bootSequence: [
      '',
      '********************************************',
      '*                                          *',
      '*           RADIO SHACK TRS-80             *',
      '*              MODEL III                   *',
      '*                                          *',
      '*    CLAUDE LANGUAGE SYSTEM V4.0           *',
      '*    (C) 2025 ANTHROPIC / TANDY CORP       *',
      '*                                          *',
      '********************************************',
      '',
      'MEMORY SIZE? ',
      '48K RAM SYSTEM',
      '',
      'TRSDOS READY',
      '',
    ],
    responseStyle: (text) => formatWithTrailer(text, 'READY', { uppercase: true }),
    systemPromptAddition: 'Format for 64-column display. Use UPPERCASE. Be direct and practical. Reference Radio Shack and early retail computing.',
  },

  atari800: {
    id: 'atari800',
    name: 'Atari 800',
    year: 1979,
    description: 'Atari\'s powerful 8-bit home computer',
    colors: {
      primary: '#5dade2',
      dim: '#2e86c1',
      bg: '#1a1a2e',
      border: '#5dade2',
    },
    prompt: 'READY\n',
    columns: 40,
    fontSize: 20,
    fontFamily: '"Courier New", Courier, monospace',
    uppercase: true,
    bootSequence: [
      '',
      '       ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄',
      '       █   A T A R I   8 0 0    █',
      '       █                        █',
      '       █   CLAUDE BASIC V4.0    █',
      '       █   (C) 2025 ANTHROPIC   █',
      '       █                        █',
      '       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀',
      '',
      'ATARI COMPUTER - MEMO PAD',
      '',
      '48K RAM SYSTEM',
      '',
      'READY',
      '',
    ],
    responseStyle: (text) => formatWithTrailer(text, 'READY', { uppercase: true }),
    systemPromptAddition: 'Format for 40-column display. Use UPPERCASE. Be friendly and accessible. Reference gaming and home entertainment.',
  },

  bbc: {
    id: 'bbc',
    name: 'BBC Micro',
    year: 1981,
    description: 'The British educational computer that taught a generation',
    colors: {
      primary: '#ffffff',
      dim: '#ffff00',
      bg: '#000000',
      border: '#ff0000',
    },
    prompt: '>',
    columns: 40,
    fontSize: 20,
    fontFamily: '"Courier New", Courier, monospace',
    bootSequence: [
      '',
      'BBC Computer 32K',
      '',
      'CLAUDE BASIC',
      '(C) 2025 Anthropic',
      '',
      '         ╔═══════════════════╗',
      '         ║  ████   ████   ██ ║',
      '         ║  █   █  █   █  █  ║',
      '         ║  ████   ████   █  ║',
      '         ║  █   █  █   █  █  ║',
      '         ║  ████   ████   ██ ║',
      '         ╚═══════════════════╝',
      '              MICRO',
      '',
      'BASIC',
      '',
    ],
    responseStyle: (text) => formatWithTrailer(text, '>', { trailingNewline: false }),
    systemPromptAddition: 'Format for 40-column display. Be educational and encouraging. Reference British computing, the BBC Computer Literacy Project, and learning.',
  },

  mac: {
    id: 'mac',
    name: 'Macintosh',
    year: 1984,
    description: 'The computer for the rest of us',
    lightMode: true,
    colors: {
      primary: '#000000',
      dim: '#666666',
      bg: '#ffffff',
      border: '#000000',
    },
    prompt: '',
    columns: 60,
    fontSize: 18,
    fontFamily: 'Geneva, "Courier New", monospace',
    bootSequence: [
      '',
      '┌──────────────────────────────────────────────────────┐',
      '│ ■ File  Edit  View  Special                         │',
      '├──────────────────────────────────────────────────────┤',
      '│                                                      │',
      '│       ┌────────────────────────────────┐             │',
      '│       │                                │             │',
      '│       │     Welcome to Macintosh       │             │',
      '│       │                                │             │',
      '│       │       ┌──────────────┐         │',
      '│       │       │  Claude AI   │',
      '│       │       │    v 4.0     │',
      '│       │       └──────────────┘         │',
      '│       │                                │',
      '│       │  (c) 2025 Anthropic Inc.       │',
      '│       │                                │',
      '│       └────────────────────────────────┘             │',
      '│                                                      │',
      '└──────────────────────────────────────────────────────┘',
      '',
    ],
    responseStyle: (text) => formatBoxed(text, {
      top: '┌─ Claude ───────────────────────────────────────────┐',
      bottom: '└────────────────────────────────────────────────────┘',
      linePrefix: '  ',
    }),
    systemPromptAddition: 'Format for 60-column display. Be friendly, approachable, and human. Use plain language. Reference creativity, design, and "the rest of us."',
  },

  amstrad: {
    id: 'amstrad',
    name: 'Amstrad CPC',
    year: 1984,
    description: 'The colorful British rival to the Spectrum',
    colors: {
      primary: '#ffff00',
      dim: '#00ffff',
      bg: '#000080',
      border: '#ffff00',
    },
    prompt: 'Ready\n',
    columns: 40,
    fontSize: 20,
    fontFamily: '"Courier New", Courier, monospace',
    bootSequence: [
      '',
      '  ╔══════════════════════════════════╗',
      '  ║  AMSTRAD 128K MICROCOMPUTER      ║',
      '  ║  ©1984 AMSTRAD CONSUMER          ║',
      '  ║  ELECTRONICS PLC                 ║',
      '  ╚══════════════════════════════════╝',
      '',
      'CLAUDE LOCOMOTIVE BASIC v4.0',
      '(c) 2025 Anthropic',
      '',
      '128K RAM, 42719 BYTES FREE',
      '',
      'Ready',
      '',
    ],
    responseStyle: (text) => formatWithTrailer(text, 'Ready'),
    systemPromptAddition: 'Format for 40-column display. Be colorful and enthusiastic. Reference gaming, tape loading, and European computing.',
  },

  atarist: {
    id: 'atarist',
    name: 'Atari ST',
    year: 1985,
    description: 'The Jackintosh - powerful 16-bit computing',
    lightMode: true,
    colors: {
      primary: '#000000',
      dim: '#555555',
      bg: '#ffffff',
      border: '#000000',
    },
    prompt: 'A:\\> ',
    columns: 80,
    fontSize: 18,
    fontFamily: '"Courier New", Courier, monospace',
    bootSequence: [
      '┌──────────────────────────────────────────────────────────────────────────────┐',
      '│  ▓▓▓▓ ATARI ST ▓▓▓▓                                           [■][□][×]    │',
      '├──────────────────────────────────────────────────────────────────────────────┤',
      '│                                                                              │',
      '│               █████╗ ████████╗ █████╗ ██████╗ ██╗                           │',
      '│              ██╔══██╗╚══██╔══╝██╔══██╗██╔══██╗██║                           │',
      '│              ███████║   ██║   ███████║██████╔╝██║                           │',
      '│              ██╔══██║   ██║   ██╔══██║██╔══██╗██║                           │',
      '│              ██║  ██║   ██║   ██║  ██║██║  ██║██║                           │',
      '│              ╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝                           │',
      '│                                                                              │',
      '│                     CLAUDE AI SYSTEM v4.0                                   │',
      '│                     1024K RAM / TOS 1.04                                    │',
      '│                                                                              │',
      '└──────────────────────────────────────────────────────────────────────────────┘',
      '',
    ],
    responseStyle: (text) => formatBoxed(text, {
      top: '┌─ Output ─────────────────────────────────────────────────────────────────────┐',
      bottom: '└──────────────────────────────────────────────────────────────────────────────┘',
      linePrefix: '│  ',
    }),
    systemPromptAddition: 'Format for 80-column display. Reference MIDI, music production, desktop publishing, and being the affordable alternative to the Mac.',
  },

  next: {
    id: 'next',
    name: 'NeXTSTEP',
    year: 1988,
    description: 'Steve Jobs\' vision of the future',
    colors: {
      primary: '#ffffff',
      dim: '#aaaaaa',
      bg: '#333333',
      border: '#000000',
    },
    prompt: 'localhost# ',
    columns: 80,
    fontSize: 18,
    fontFamily: '"Courier New", Courier, monospace',
    bootSequence: [
      '',
      '╔══════════════════════════════════════════════════════════════════════════════╗',
      '║                                                                              ║',
      '║                              ███╗   ██╗███████╗██╗  ██╗████████╗             ║',
      '║                              ████╗  ██║██╔════╝╚██╗██╔╝╚══██╔══╝             ║',
      '║                              ██╔██╗ ██║█████╗   ╚███╔╝    ██║                ║',
      '║                              ██║╚██╗██║██╔══╝   ██╔██╗    ██║                ║',
      '║                              ██║ ╚████║███████╗██╔╝ ██╗   ██║                ║',
      '║                              ╚═╝  ╚═══╝╚══════╝╚═╝  ╚═╝   ╚═╝                ║',
      '║                                                                              ║',
      '║                         NeXTSTEP Release 3.3                                 ║',
      '║                         Claude AI Framework 4.0                             ║',
      '║                         (c) 2025 Anthropic Inc.                             ║',
      '║                                                                              ║',
      '╚══════════════════════════════════════════════════════════════════════════════╝',
      '',
      'Mach kernel loaded.',
      'Starting NeXTSTEP...',
      '',
      'localhost login: claude',
      'Last login: Thu Feb  5 12:00:00 on console',
      '',
    ],
    responseStyle: (text) => formatPlain(text),
    systemPromptAddition: 'Format for 80-column display. Be sophisticated and forward-thinking. Reference object-oriented programming, the web (invented on NeXT), and the future of computing.',
  },

  pet: {
    id: 'pet',
    name: 'Commodore PET',
    year: 1977,
    description: 'The first all-in-one personal computer',
    colors: {
      primary: '#00ff00',
      dim: '#009900',
      bg: '#000000',
      border: '#00ff00',
    },
    prompt: 'READY.\n',
    columns: 40,
    fontSize: 20,
    fontFamily: '"Courier New", Courier, monospace',
    uppercase: true,
    bootSequence: [
      '',
      '*** COMMODORE BASIC ***',
      '',
      ' 7167 BYTES FREE',
      '',
      '    ╔══════════════════════════════╗',
      '    ║   ██████╗ ███████╗████████╗  ║',
      '    ║   ██╔══██╗██╔════╝╚══██╔══╝  ║',
      '    ║   ██████╔╝█████╗     ██║     ║',
      '    ║   ██╔═══╝ ██╔══╝     ██║     ║',
      '    ║   ██║     ███████╗   ██║     ║',
      '    ║   ╚═╝     ╚══════╝   ╚═╝     ║',
      '    ╚══════════════════════════════╝',
      '',
      'CLAUDE SYSTEM V4.0',
      '(C) 2025 ANTHROPIC',
      '',
      'READY.',
      '',
    ],
    responseStyle: (text) => formatWithTrailer(text, 'READY.', { uppercase: true }),
    systemPromptAddition: 'Format for 40-column display. Use UPPERCASE. Be pioneering and enthusiastic. Reference the dawn of personal computing and PETSCII graphics.',
  },

  vic20: {
    id: 'vic20',
    name: 'VIC-20',
    year: 1980,
    description: 'The friendly computer',
    colors: {
      primary: '#55ffff',
      dim: '#aaaaff',
      bg: '#352879',
      border: '#55ffff',
    },
    prompt: 'READY.\n',
    columns: 22,
    fontSize: 22,
    fontFamily: '"Courier New", Courier, monospace',
    uppercase: true,
    bootSequence: [
      '',
      '**** CBM BASIC V2 ****',
      '',
      ' 3583 BYTES FREE',
      '',
      '  ╔════════════════╗',
      '  ║    VIC-20      ║',
      '  ║   THE FRIENDLY ║',
      '  ║    COMPUTER    ║',
      '  ╚════════════════╝',
      '',
      'CLAUDE V4.0',
      '(C)2025 ANTHROPIC',
      '',
      'READY.',
      '',
    ],
    responseStyle: (text) => formatWithTrailer(text, 'READY.', { uppercase: true }),
    systemPromptAddition: 'Format for 22-column display - very short lines! Use UPPERCASE. Be extremely concise. Be friendly and welcoming. Reference being a gateway to computing for many.',
  },

  ti994a: {
    id: 'ti994a',
    name: 'TI-99/4A',
    year: 1981,
    description: 'Texas Instruments\' colorful home computer',
    colors: {
      primary: '#00ff00',
      dim: '#00aa00',
      bg: '#000000',
      border: '#00ff00',
    },
    prompt: '>',
    columns: 32,
    fontSize: 20,
    fontFamily: '"Courier New", Courier, monospace',
    uppercase: true,
    bootSequence: [
      '',
      '  ████████╗ ██╗',
      '  ╚══██╔══╝ ██║',
      '     ██║    ██║',
      '     ██║    ██║',
      '     ██║    ██║',
      '     ╚═╝    ╚═╝',
      '',
      'TEXAS INSTRUMENTS',
      'HOME COMPUTER',
      '',
      '  ╔════════════════════╗',
      '  ║  CLAUDE TI BASIC   ║',
      '  ║     VERSION 4.0    ║',
      '  ║  (C) 2025 ANTHROPIC║',
      '  ╚════════════════════╝',
      '',
      'READY-PRESS ANY KEY',
      '',
      '',
    ],
    responseStyle: (text) => formatWithTrailer(text, '** DONE **\n>', {
      uppercase: true,
      trailingNewline: false,
    }),
    systemPromptAddition: 'Format for 32-column display. Use UPPERCASE. Be educational. Reference speech synthesis, education, and Texas Instruments.',
  },

  coco: {
    id: 'coco',
    name: 'TRS-80 CoCo',
    year: 1980,
    description: 'The Color Computer - Tandy\'s colorful home machine',
    colors: {
      primary: '#00ff00',
      dim: '#ff8000',
      bg: '#000000',
      border: '#00ff00',
    },
    prompt: 'OK\n',
    columns: 32,
    fontSize: 20,
    fontFamily: '"Courier New", Courier, monospace',
    uppercase: true,
    bootSequence: [
      '',
      '╔════════════════════════════════╗',
      '║     TANDY COLOR COMPUTER       ║',
      '║          EXTENDED BASIC        ║',
      '║                                ║',
      '║   ████████╗ ████████╗ ████████╗║',
      '║   ██╔════╝ ██╔═════╝ ██╔═════╝║',
      '║   ██║      ██║       ██║      ║',
      '║   ██║      ██║       ██║      ║',
      '║   ╚═╝      ╚═╝       ╚═╝      ║',
      '║      C O L O R                 ║',
      '╚════════════════════════════════╝',
      '',
      'CLAUDE EXTENDED BASIC V4.0',
      '(C) 2025 ANTHROPIC',
      '',
      'OK',
      '',
    ],
    responseStyle: (text) => formatWithTrailer(text, 'OK', { uppercase: true }),
    systemPromptAddition: 'Format for 32-column display. Use UPPERCASE. Be enthusiastic about graphics and games. Reference OS-9 and the CoCo community.',
  },

  msxsystem: {
    id: 'msxsystem',
    name: 'MSX',
    year: 1983,
    description: 'The Japanese home computer standard',
    colors: {
      primary: '#ffffff',
      dim: '#21c842',
      bg: '#000000',
      border: '#21c842',
    },
    prompt: 'Ok\n',
    columns: 40,
    fontSize: 20,
    fontFamily: '"Courier New", Courier, monospace',
    bootSequence: [
      '',
      '╔══════════════════════════════════════╗',
      '║           MSX SYSTEM                 ║',
      '║    MICROSOFT EXTENDED BASIC          ║',
      '╚══════════════════════════════════════╝',
      '',
      '       ███╗   ███╗███████╗██╗  ██╗',
      '       ████╗ ████║██╔════╝╚██╗██╔╝',
      '       ██╔████╔██║███████╗ ╚███╔╝',
      '       ██║╚██╔╝██║╚════██║ ██╔██╗',
      '       ██║ ╚═╝ ██║███████║██╔╝ ██╗',
      '       ╚═╝     ╚═╝╚══════╝╚═╝  ╚═╝',
      '',
      'CLAUDE-BASIC Version 4.0',
      '(C) 2025 Anthropic',
      '28815 Bytes free',
      '',
      'Ok',
      '',
    ],
    responseStyle: (text) => formatWithTrailer(text, 'Ok'),
    systemPromptAddition: 'Format for 40-column display. Reference Japanese gaming culture, Konami games, and the international MSX community.',
  },
};

// 80s color themes (can be applied to any emulator)
export const COLOR_THEMES = {
  default: null, // Use emulator's default colors
  synthwave: {
    primary: '#ff00ff',
    dim: '#00ffff',
    bg: '#1a0a2e',
    border: '#ff00ff',
    gradient: 'linear-gradient(180deg, #1a0a2e 0%, #0d0d2b 50%, #0a0a1a 100%)',
  },
  miami: {
    primary: '#00ffff',
    dim: '#ff6ec7',
    bg: '#0d0221',
    border: '#00ffff',
    gradient: 'linear-gradient(180deg, #0d0221 0%, #150530 50%, #1a0a3a 100%)',
  },
  sunset: {
    primary: '#ff6b35',
    dim: '#f7c59f',
    bg: '#1a0a0a',
    border: '#ff6b35',
    gradient: 'linear-gradient(180deg, #1a0a0a 0%, #2d1810 50%, #1a0f0a 100%)',
  },
};
